[package]
name = "euler_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
euler = { path = "../euler" }
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }

[[bin]]
name = "euler"
path = "src/main.rs"
