[package]
name = "euler_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
euler = { path = "../euler" }
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
num = "0.4.3"
itertools = "0.14.0"
rayon = "1.11.0"

[[bin]]
name = "euler"
path = "src/main.rs"
